"""Generating, starting and stopping the Metaflow flow that runs the shards.

Each ``submit_batch`` gets its own flow file, rendered from :data:`FLOW_TEMPLATE`
with the run's settings baked in as a literal. Metaflow re-imports the flow file
inside every Batch container, so decorator arguments must not depend on the
environment of the submitting process; a literal is identical on both sides.

The flow file is written to a fresh directory together with a copy of this package
and of any ``code_paths``. Metaflow ships that directory to the Batch jobs as the
flow's code package and puts it on ``sys.path`` there, so the image does not need
this package installed (it still needs Harbor, or a bootstrap that installs it).

    start (submitting host) -> run_shard (foreach shard; @batch) -> join -> end
"""

from __future__ import annotations

import json
import os
import shutil
import signal
import subprocess
import sys
import tempfile
from dataclasses import asdict, dataclass, field
from pathlib import Path
from string import Template

FLOW_FILE_NAME = "harbor_trials_flow.py"
PACKAGE_DIR = Path(__file__).resolve().parent

#: SIGINT to the flow (Metaflow stops its tasks), then SIGTERM, then SIGKILL.
STOP_GRACE_SEC = 60.0


@dataclass
class FlowSettings:
    """Everything the generated flow needs. See the README's configuration table."""

    local: bool = False
    image: str | None = None
    queue: str | None = None
    iam_role: str | None = None
    cpu: int = 4
    memory: int = 16384
    timeout_sec: int = 24 * 3600
    work_dir: str = "/var/lib/harbor-work"
    docker_socket: str = "/var/run/docker.sock"
    privileged: bool = False
    env: dict[str, str] = field(default_factory=dict)
    secrets: list[str] = field(default_factory=list)
    cleanup_work_dir: bool = True
    job_user: str | None = None

    def batch_kwargs(self) -> dict | None:
        """Arguments for Metaflow's ``@batch``, or ``None`` to run steps locally."""
        if self.local:
            return None
        kwargs: dict = {
            "image": self.image,
            "cpu": int(self.cpu),
            "memory": int(self.memory),
            # Trials start sibling containers through the host's Docker daemon, which
            # resolves bind mounts on the host: the work dir must be the same path
            # inside the job container and on the host.
            "host_volumes": [self.docker_socket, self.work_dir],
        }
        if self.queue:
            kwargs["queue"] = self.queue
        if self.iam_role:
            kwargs["iam_role"] = self.iam_role
        if self.privileged:
            kwargs["privileged"] = True
        return kwargs


FLOW_TEMPLATE = Template('''\
"""Generated by harbor-metaflow-backend for one run. Do not edit."""

import json
import os

from metaflow import FlowSpec, Parameter, current, step

SETTINGS = json.loads($settings)

if SETTINGS["batch"] is not None and SETTINGS["job_user"]:
    # Job definitions get containerProperties.user (Metaflow's @batch has no option).
    from harbor_metaflow_backend.jobdef import install_job_user

    install_job_user(SETTINGS["job_user"])


def _decorate(func):
    from metaflow import batch, environment, secrets, timeout

    if SETTINGS["secrets"]:
        func = secrets(sources=SETTINGS["secrets"])(func)
    if SETTINGS["env"]:
        func = environment(vars=SETTINGS["env"])(func)
    if SETTINGS["timeout_sec"]:
        func = timeout(seconds=SETTINGS["timeout_sec"])(func)
    if SETTINGS["batch"] is not None:
        func = batch(**SETTINGS["batch"])(func)
    return func


class HarborTrialsFlow(FlowSpec):
    run_uri = Parameter("run_uri", required=True, help="Staged run root")

    @step
    def start(self):
        from harbor_metaflow_backend.store import open_store
        from harbor_metaflow_backend.worker import load_manifest

        manifest = load_manifest(open_store(self.run_uri))
        self.shards = list(range(len(manifest["shards"])))
        self.next(self.run_shard, foreach="shards")

    @_decorate
    @step
    def run_shard(self):
        from harbor_metaflow_backend.store import open_store
        from harbor_metaflow_backend.worker import run_shard

        shard = int(self.input)
        work_dir = os.path.join(
            SETTINGS["work_dir"], "harbor-metaflow", current.flow_name,
            str(current.run_id), str(shard))
        self.summary = run_shard(open_store(self.run_uri), shard, work_dir,
                                 cleanup=SETTINGS["cleanup_work_dir"])
        print(json.dumps({"shard": shard, **self.summary}))
        self.next(self.join)

    @step
    def join(self, inputs):
        self.summaries = [i.summary for i in inputs]
        self.next(self.end)

    @step
    def end(self):
        pass


if __name__ == "__main__":
    HarborTrialsFlow()
''')


def render_flow(settings: FlowSettings) -> str:
    data = asdict(settings)
    data["batch"] = settings.batch_kwargs()
    return FLOW_TEMPLATE.substitute(settings=repr(json.dumps(data, sort_keys=True)))


class FlowProcess:
    """A running ``python harbor_trials_flow.py run`` in its own process group."""

    def __init__(self, proc: subprocess.Popen, log_path: Path, flow_dir: Path):
        self.proc = proc
        self.log_path = log_path
        self.flow_dir = flow_dir

    def poll(self) -> int | None:
        return self.proc.poll()

    def stop(self, grace: float = STOP_GRACE_SEC) -> None:
        for sig in (signal.SIGINT, signal.SIGTERM, signal.SIGKILL):
            if self.proc.poll() is not None:
                return
            try:
                os.killpg(self.proc.pid, sig)
            except ProcessLookupError:
                return
            try:
                self.proc.wait(timeout=grace)
            except subprocess.TimeoutExpired:
                continue

    def cleanup(self) -> None:
        """Remove the generated flow dir once the flow has exited."""
        if self.proc.poll() is not None:
            shutil.rmtree(self.flow_dir, ignore_errors=True)


def _ignore_caches(_dir: str, names: list[str]) -> set[str]:
    skip = ("__pycache__", ".pytest_cache")
    return {n for n in names if n in skip or n.endswith(".pyc")}


def write_flow_dir(
    flow_dir: Path, settings: FlowSettings, code_paths: list[str] | None = None
) -> Path:
    """Write the flow file, a copy of this package and the ``code_paths``.

    Everything in ``flow_dir`` with one of Metaflow's package suffixes (``.py`` by
    default) is shipped to the Batch jobs and importable there by its top-level name.
    """
    flow_dir.mkdir(parents=True, exist_ok=True)
    taken = {FLOW_FILE_NAME, PACKAGE_DIR.name}
    shutil.copytree(PACKAGE_DIR, flow_dir / PACKAGE_DIR.name, ignore=_ignore_caches)
    for raw in code_paths or []:
        src = Path(raw).expanduser().resolve()
        if src.name in taken:
            raise ValueError(f"code_paths: {src.name!r} is already in the flow dir")
        taken.add(src.name)
        if src.is_dir():
            shutil.copytree(src, flow_dir / src.name, ignore=_ignore_caches)
        elif src.is_file():
            shutil.copy2(src, flow_dir / src.name)
        else:
            raise FileNotFoundError(f"code_paths: {raw} does not exist")
    flow_file = flow_dir / FLOW_FILE_NAME
    flow_file.write_text(render_flow(settings))
    return flow_file


class MetaflowLauncher:
    """Renders the flow into a temporary dir and runs it with Metaflow."""

    def __init__(
        self,
        settings: FlowSettings,
        python: str | None = None,
        max_workers: int = 16,
        extra_args: list[str] | None = None,
        code_paths: list[str] | None = None,
        package_suffixes: list[str] | None = None,
    ):
        self.settings = settings
        self.python = python or sys.executable
        self.max_workers = int(max_workers)
        self.extra_args = list(extra_args or [])
        self.code_paths = list(code_paths or [])
        self.package_suffixes = list(package_suffixes or [])

    def command(self, flow_file: Path, run_uri: str, n_shards: int) -> list[str]:
        top = ["--no-pylint"]
        if self.package_suffixes:
            top += ["--package-suffixes", ",".join(self.package_suffixes)]
        return [
            self.python,
            str(flow_file),
            *top,
            "run",
            "--run_uri",
            run_uri,
            "--max-workers",
            str(self.max_workers),
            "--max-num-splits",
            str(max(100, n_shards)),
            *self.extra_args,
        ]

    def start(self, run_uri: str, n_shards: int, log_path: Path) -> FlowProcess:
        flow_dir = Path(tempfile.mkdtemp(prefix="harbor-metaflow-"))
        try:
            flow_file = write_flow_dir(flow_dir, self.settings, self.code_paths)
        except BaseException:
            shutil.rmtree(flow_dir, ignore_errors=True)
            raise
        log_path.parent.mkdir(parents=True, exist_ok=True)
        with open(log_path, "ab") as log:
            proc = subprocess.Popen(
                self.command(flow_file, run_uri, n_shards),
                cwd=flow_dir,
                stdout=log,
                stderr=subprocess.STDOUT,
                start_new_session=True,
            )
        return FlowProcess(proc, log_path, flow_dir)


def terminate_batch_jobs(job_ids: list[str], reason: str) -> None:
    """Terminate AWS Batch jobs (the workers record their own job ids)."""
    import boto3

    client = boto3.client("batch")
    for job_id in job_ids:
        client.terminate_job(jobId=job_id, reason=reason[:1024])
